# In: ID, a collection
# Result: top concepts in the collection + their narrower concepts in the same collection. In other words: a hierarchy within a collection.
{
  memberOf(_:ID)
  topConceptOf @single
  # level 1
  id @single
  ... conceptFields
  narrower @optional {
    memberOf(_:ID)
    # level 2
    id @single
    ... conceptFields
    narrower @optional {
      memberOf(_:ID)
      # level 3
      id @single
      ... conceptFields
      narrower @optional {
        memberOf(_:ID)
        # level 4
        id @single
        ... conceptFields
        narrower @optional {
          memberOf(_:ID)
          # level 5 (is enough for all known collections)
          id @single
          ... conceptFields
        }
      }
    }
  }
}

fragment conceptFields on Concept {
  prefLabel @single
  altLabel @optional
  definition @single @optional
}

